name: JMComic_Daily_Sync
on:
  schedule:
    - cron: '0 22 * * *' # 北京时间每天早上 6 点运行
  workflow_dispatch:      # 支持手动触发

jobs:
  run-and-save:
    runs-on: ubuntu-latest
    # 必须给予写入权限，才能把账本推回仓库
    permissions:
      contents: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: pip install jmcomic requests

      - name: 运行爬虫
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python main.py

      - name: 保存下载记录到仓库
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add downloaded_ids.txt
          # 只有在账本有变化时才提交，防止报错
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update history [skip ci]" && git push)
